// ============================================
// SPHIRIA+ MOCK DATA
// ============================================

export const agents = [
  {
    id: "strategy",
    name: "StrategyAgent",
    role: "Business Intelligence",
    status: "active",
    tasksCompleted: 142,
    accuracy: 94,
    lastAction: "Analyzed Q2 growth targets for 3 clients",
    icon: "🧠",
    color: "#8b5cf6",
    uptime: "99.2%",
    avgResponseTime: "1.4s",
  },
  {
    id: "marketing",
    name: "MarketingAgent",
    role: "Campaign & Content",
    status: "active",
    tasksCompleted: 387,
    accuracy: 91,
    lastAction: "Generated 12 ad copy variants for TechStart",
    icon: "📣",
    color: "#6366f1",
    uptime: "98.8%",
    avgResponseTime: "2.1s",
  },
  {
    id: "analytics",
    name: "AnalyticsAgent",
    role: "Data & Insights",
    status: "processing",
    tasksCompleted: 1204,
    accuracy: 97,
    lastAction: "Running anomaly detection on campaign CTR",
    icon: "📊",
    color: "#22d3ee",
    uptime: "99.9%",
    avgResponseTime: "0.8s",
  },
  {
    id: "lead",
    name: "LeadAgent",
    role: "Prospect & Outreach",
    status: "active",
    tasksCompleted: 231,
    accuracy: 88,
    lastAction: "Qualified 7 leads from LinkedIn campaign",
    icon: "🎯",
    color: "#34d399",
    uptime: "97.5%",
    avgResponseTime: "3.2s",
  },
  {
    id: "support",
    name: "SupportAgent",
    role: "Customer Interaction",
    status: "active",
    tasksCompleted: 892,
    accuracy: 96,
    lastAction: "Resolved 4 tickets via WhatsApp channel",
    icon: "💬",
    color: "#f59e0b",
    uptime: "99.5%",
    avgResponseTime: "0.5s",
  },
  {
    id: "content",
    name: "ContentAgent",
    role: "Content Generation",
    status: "idle",
    tasksCompleted: 563,
    accuracy: 89,
    lastAction: "Scheduled 5 social posts for next week",
    icon: "✍️",
    color: "#ec4899",
    uptime: "96.3%",
    avgResponseTime: "4.1s",
  },
  {
    id: "execution",
    name: "ExecutionAgent",
    role: "Workflow Automation",
    status: "active",
    tasksCompleted: 2041,
    accuracy: 99,
    lastAction: "Pushed campaign to HubSpot & Meta Ads",
    icon: "⚡",
    color: "#f97316",
    uptime: "99.7%",
    avgResponseTime: "0.3s",
  },
  {
    id: "audit",
    name: "AuditAgent",
    role: "Quality & Compliance",
    status: "active",
    tasksCompleted: 3102,
    accuracy: 100,
    lastAction: "Validated 18 agent outputs — 0 issues",
    icon: "🛡️",
    color: "#64748b",
    uptime: "100%",
    avgResponseTime: "0.2s",
  },
];

export const kpiMetrics = [
  {
    id: "revenue",
    label: "MRR Growth",
    value: "$48,200",
    change: +18.4,
    trend: "up",
    sparkline: [28, 32, 29, 38, 40, 36, 44, 48],
    icon: "💰",
    color: "#34d399",
  },
  {
    id: "leads",
    label: "Leads Generated",
    value: "1,284",
    change: +34.2,
    trend: "up",
    sparkline: [520, 680, 740, 820, 900, 1050, 1180, 1284],
    icon: "🎯",
    color: "#8b5cf6",
  },
  {
    id: "campaigns",
    label: "Active Campaigns",
    value: "23",
    change: +4.5,
    trend: "up",
    sparkline: [14, 16, 17, 18, 20, 21, 22, 23],
    icon: "📣",
    color: "#6366f1",
  },
  {
    id: "automation",
    label: "Tasks Automated",
    value: "8,024",
    change: +61.7,
    trend: "up",
    sparkline: [1200, 2100, 3400, 4500, 5800, 6700, 7500, 8024],
    icon: "⚡",
    color: "#22d3ee",
  },
];

export const revenueChartData = [
  { month: "Oct", revenue: 22000, leads: 480, automations: 1200 },
  { month: "Nov", revenue: 28400, leads: 620, automations: 2100 },
  { month: "Dec", revenue: 31200, leads: 710, automations: 3000 },
  { month: "Jan", revenue: 35800, leads: 840, automations: 4200 },
  { month: "Feb", revenue: 39100, leads: 980, automations: 5800 },
  { month: "Mar", revenue: 44600, leads: 1120, automations: 6900 },
  { month: "Apr", revenue: 48200, leads: 1284, automations: 8024 },
];

export const activityFeed = [
  {
    id: 1,
    agent: "MarketingAgent",
    action: "Generated Q2 email campaign sequence for NexaRetail",
    time: "2 min ago",
    type: "success",
    icon: "📣",
  },
  {
    id: 2,
    agent: "AnalyticsAgent",
    action: "Anomaly detected: CTR spike +340% on Meta Ads — investigating",
    time: "8 min ago",
    type: "warning",
    icon: "📊",
  },
  {
    id: 3,
    agent: "SupportAgent",
    action: "Resolved 6 customer tickets via WhatsApp — avg. 42s response",
    time: "15 min ago",
    type: "success",
    icon: "💬",
  },
  {
    id: 4,
    agent: "LeadAgent",
    action: "Qualified 3 high-intent leads from LinkedIn — forwarded to CRM",
    time: "22 min ago",
    type: "success",
    icon: "🎯",
  },
  {
    id: 5,
    agent: "ExecutionAgent",
    action: "Triggered HubSpot sequence for 124 warm leads",
    time: "35 min ago",
    type: "success",
    icon: "⚡",
  },
  {
    id: 6,
    agent: "AuditAgent",
    action: "Reviewed 42 agent decisions — 100% compliance score",
    time: "1 hr ago",
    type: "success",
    icon: "🛡️",
  },
  {
    id: 7,
    agent: "StrategyAgent",
    action: "Generated Q3 growth strategy doc for 2 enterprise clients",
    time: "2 hr ago",
    type: "success",
    icon: "🧠",
  },
  {
    id: 8,
    agent: "ContentAgent",
    action: "Scheduled 14 social posts across 3 client accounts",
    time: "3 hr ago",
    type: "success",
    icon: "✍️",
  },
];

export const clients = [
  {
    id: "c1",
    name: "NexaRetail",
    industry: "E-commerce",
    plan: "Scale",
    status: "active",
    agents: 6,
    mrr: "$799",
    lastActive: "2 min ago",
    health: 98,
    avatar: "N",
    color: "#8b5cf6",
    integrations: ["Shopify", "Meta Ads", "HubSpot"],
  },
  {
    id: "c2",
    name: "TechStart Labs",
    industry: "SaaS",
    plan: "Growth",
    status: "active",
    agents: 4,
    mrr: "$299",
    lastActive: "18 min ago",
    health: 94,
    avatar: "T",
    color: "#22d3ee",
    integrations: ["Stripe", "LinkedIn Ads", "Slack"],
  },
  {
    id: "c3",
    name: "Bloom Agency",
    industry: "Marketing",
    plan: "Scale",
    status: "active",
    agents: 7,
    mrr: "$799",
    lastActive: "1 hr ago",
    health: 87,
    avatar: "B",
    color: "#34d399",
    integrations: ["Google Ads", "Mailchimp", "Zapier"],
  },
  {
    id: "c4",
    name: "UrbanEstate",
    industry: "Real Estate",
    plan: "Starter",
    status: "trial",
    agents: 2,
    mrr: "$99",
    lastActive: "4 hr ago",
    health: 76,
    avatar: "U",
    color: "#f59e0b",
    integrations: ["Zoho CRM", "WhatsApp"],
  },
  {
    id: "c5",
    name: "HealthPulse",
    industry: "Healthcare",
    plan: "Enterprise",
    status: "active",
    agents: 8,
    mrr: "$2,200",
    lastActive: "Just now",
    health: 99,
    avatar: "H",
    color: "#ec4899",
    integrations: ["Salesforce", "Twilio", "Slack"],
  },
];

export const workflows = [
  {
    id: "wf1",
    name: "Lead Nurture Sequence",
    client: "NexaRetail",
    status: "running",
    steps: 7,
    completedSteps: 5,
    triggeredAt: "2h ago",
    agents: ["LeadAgent", "MarketingAgent", "ExecutionAgent"],
  },
  {
    id: "wf2",
    name: "Weekly Analytics Report",
    client: "TechStart Labs",
    status: "running",
    steps: 4,
    completedSteps: 3,
    triggeredAt: "30min ago",
    agents: ["AnalyticsAgent", "ContentAgent"],
  },
  {
    id: "wf3",
    name: "Q2 Campaign Launch",
    client: "Bloom Agency",
    status: "pending",
    steps: 10,
    completedSteps: 0,
    triggeredAt: "Scheduled: Tomorrow 09:00",
    agents: ["StrategyAgent", "MarketingAgent", "ContentAgent", "ExecutionAgent"],
  },
  {
    id: "wf4",
    name: "Customer Support Auto-Triage",
    client: "HealthPulse",
    status: "running",
    steps: 3,
    completedSteps: 3,
    triggeredAt: "Always On",
    agents: ["SupportAgent", "AuditAgent"],
  },
];

export const insightCards = [
  {
    id: "i1",
    type: "opportunity",
    title: "Meta Ads CTR spike — act now",
    body: "NexaRetail's retargeting campaign is showing 340% above-average CTR. AnalyticsAgent recommends increasing daily budget by 40% before the audience cools.",
    confidence: 92,
    agent: "AnalyticsAgent",
    time: "8 min ago",
    action: "Increase Budget",
  },
  {
    id: "i2",
    type: "warning",
    title: "Churn risk: UrbanEstate",
    body: "Usage has dropped 62% over the last 14 days. Recommend scheduling a strategy call and sending a re-engagement email via SupportAgent.",
    confidence: 87,
    agent: "StrategyAgent",
    time: "1 hr ago",
    action: "Send Re-engagement",
  },
  {
    id: "i3",
    type: "success",
    title: "Bloom Agency campaign hit KPIs",
    body: "Q1 Google Ads campaign achieved 118% of the conversion target. MarketingAgent has already drafted a Q2 scaled version for your review.",
    confidence: 99,
    agent: "MarketingAgent",
    time: "3 hr ago",
    action: "Review Q2 Draft",
  },
];

export const navItems = [
  { id: "dashboard", label: "Dashboard", icon: "LayoutDashboard", path: "/" },
  { id: "agents", label: "Agent Mesh", icon: "Bot", path: "/agents" },
  { id: "workflows", label: "Workflows", icon: "GitBranch", path: "/workflows" },
  { id: "clients", label: "Clients", icon: "Users", path: "/clients" },
  { id: "analytics", label: "Analytics", icon: "BarChart3", path: "/analytics" },
  { id: "memory", label: "Knowledge Graph", icon: "Brain", path: "/memory" },
  { id: "integrations", label: "Integrations", icon: "Plug", path: "/integrations" },
  { id: "settings", label: "Settings", icon: "Settings", path: "/settings" },
];
